[project]
name = "coolcover-company"
version = "0.1.0"
description = ""
authors = [
    { name = "Mehdi-H", email = "mehdi.houacine7@gmail.com" }
]
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.111.0",
    "pydantic>=2.7.1",
    "uvicorn>=0.29.0",
    "json-schema-for-humans>=1.0.0",
]

[dependency-groups]
dev = [
    "ruff>=0.4.2",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/coolcover_company"]
